language: node_js
node_js:
  - "8"
cache: yarn
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
before_install:
  - npm install -g @angular/cli
script: ng build --prod