language: node_js
node_js:
  - "8"
cache: yarn
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
before_install:
  - npm install -g @angular/cli
script: ng build --prod